######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 21 13:16:52 2013
######################################################################

TEMPLATE = lib
TARGET = dbus
DEPENDPATH += .
INCLUDEPATH += .
QT += dbus

# Input
HEADERS += DBusModule.hpp
SOURCES += DBusModule.cpp
